### ISSUE TITLE
LOTS of missing images

### ISSUE THREAD

**Issue by FunniMan1** [Sushi8756/Cookie-Clicker-2.031#1]
When I was playing cookie clicker i found that most of the assets for milk were not there once i passed Honey Milk, I also encountered that the pet the dragon image and the dragon icons themselfs were bugged out. Could you fix this problem

**Comment by Sushi8756** [comment]
It should be fixed for most textures in the new update 1.1.0! 
https://github.com/Sushi8756/Cookie-Clicker-2.048
